version: "3.8"

services:

    db:
        container_name: sds4_db
        build:
            context: ./docker/db
            dockerfile: Dockerfile
        ports:
            - "5432:5432"
        volumes:
            - ./storage/postgres/:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sds4
        networks:
            - sds4

    app:
        container_name: sds4_app
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - ./:/app/
            - ./docker/php/app.conf:/etc/supervisor/conf.d/app.conf
            - ./docker/php/supervisord.conf:/etc/supervisor/supervisord.conf
        depends_on:
            - db
        networks:
            - sds4
        expose:
            - 9000
        entrypoint: ["docker/php/init_script.sh"]

    web:
        image: nginx:latest
        container_name: sds4_web
        ports:
            - "80:80"
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - sds4

networks:
    sds4:
        driver: bridge
        ipam:
            config:
                -   subnet: ${DOCKER_NETWORK}




